knp_snappy:
    pdf:
        enabled:    true
        binary:     "\"C:\\Program Filmes\\wkhtmltopdf\\bin\\wkhtmtopdf.exe\""
        options:    []
    image:
        enabled:    true
        binary:     "\"C:\\Program Filmes\\wkhtmltopdf\\bin\\wkhtmtoimage.exe\""
        options:    []
